import groovy.json.JsonSlurperClassic

def jsonParse(def json) {
  new groovy.json.JsonSlurperClassic().parseText(json)
}
pipeline {
    agent none
    stages {
        stage('Example 1') {
      agent any
      options {
        // Timeout counter starts BEFORE agent is allocated
        timeout(time: 1, unit: 'SECONDS')
      }
      steps {
        echo 'Hello World'
      }
        }
    }
}

